const TEST_FOLDER_PATH = './tests/';
const INPUT_FOLDER_PATH = TEST_FOLDER_PATH + 'input/';
const CORRRECT_OUTPUT_FOLDER_PATH = TEST_FOLDER_PATH + 'output/';
const INPUT_DIAGRAMS_FOLDER_PATH = TEST_FOLDER_PATH + 'inputDiagrams/';
const EXECUTABLE_PATH = './exe/';
const TEST_PREFIX = 'gailis.i';
const TEST_RESULT_PREFIX = 'gailis.o';
const PROGRAM_DEFAULT_INPUT_PATH = './' + TEST_PREFIX + 'n';
const PROGRAM_DEFAULT_OUTPUT_PATH = './' + TEST_RESULT_PREFIX + 'ut';

module.exports = {
    TEST_FOLDER_PATH,
    INPUT_FOLDER_PATH,
    CORRRECT_OUTPUT_FOLDER_PATH,
    EXECUTABLE_PATH,
    TEST_PREFIX,
    TEST_RESULT_PREFIX,
    PROGRAM_DEFAULT_INPUT_PATH,
    PROGRAM_DEFAULT_OUTPUT_PATH,
    INPUT_DIAGRAMS_FOLDER_PATH
}